#!/bin/bash
# GUIA RÁPIDO DE INÍCIO - Constituição Financeira Pessoal

echo "================================"
echo "🚀 GUIA DE INICIO RÁPIDO"
echo "================================"
echo ""

# ============================================
echo "1️⃣  Verificar se PostgreSQL está rodando..."
echo "================================"
echo "Windows:"
echo "  services.msc -> buscar 'PostgreSQL' -> Iniciar"
echo ""
echo "Linux:"
echo "  sudo systemctl start postgresql"
echo ""
echo "macOS:"
echo "  brew services start postgresql"
echo ""

# ============================================
echo "2️⃣  Criar banco de dados (se não existir)..."
echo "================================"
echo "psql -U postgres"
echo "CREATE DATABASE financas_pessoais;"
echo "\q"
echo ""

# ============================================
echo "3️⃣  Configurar variáveis de ambiente..."
echo "================================"
echo "Copie .env.example para .env e configure:"
echo "  cp .env.example .env"
echo ""
echo "Edite os valores conforme necessário:"
echo "  - DB_URL"
echo "  - DB_USER"
echo "  - DB_PASSWORD"
echo "  - JWT_KEY"
echo ""

# ============================================
echo "4️⃣  Iniciar o Backend (Spring Boot)..."
echo "================================"
echo "cd pessoais"
echo "./mvnw spring-boot:run"
echo ""
echo "✅ Backend deve estar rodando em http://localhost:8080"
echo ""

# ============================================
echo "5️⃣  Servir o Frontend (HTML/CSS/JS)..."
echo "================================"
echo "Opção A: Python (Built-in)"
echo "  cd financas-frontend"
echo "  python -m http.server 8000"
echo ""
echo "Opção B: Node.js (http-server)"
echo "  npm install -g http-server"
echo "  cd financas-frontend"
echo "  http-server -p 8000"
echo ""
echo "Opção C: Live Server (VS Code)"
echo "  Instale extensão 'Live Server'"
echo "  Clique direito em index.html -> 'Open with Live Server'"
echo ""
echo "✅ Frontend deve estar rodando em http://localhost:8000"
echo ""

# ============================================
echo "6️⃣  Testar Endpoints com Insomnia/Postman..."
echo "================================"
echo ""
echo "📍 REGISTRO:"
echo "POST http://localhost:8080/auth/register"
echo "Body: {\"email\":\"teste@test.com\",\"password\":\"senha123\"}"
echo ""
echo "📍 LOGIN:"
echo "POST http://localhost:8080/auth/login"
echo "Body: {\"email\":\"teste@test.com\",\"password\":\"senha123\"}"
echo ""
echo "📍 VER PERFIL COMPLETO:"
echo "GET http://localhost:8080/perfil/completo"
echo "Header: Authorization: Bearer {seu_token}"
echo ""
echo "📍 ATUALIZAR DADOS:"
echo "PUT http://localhost:8080/perfil/atualizar-dados"
echo "Header: Authorization: Bearer {seu_token}"
echo "Body: {\"firstName\":\"João\",\"lastName\":\"Silva\",\"age\":30}"
echo ""
echo "📍 CONFIGURAR CONSTITUIÇÃO:"
echo "POST http://localhost:8080/perfil/setup"
echo "Header: Authorization: Bearer {seu_token}"
echo "Body: {\"investmentPercent\":30,\"reservePercent\":10,\"taxPercent\":5}"
echo ""
echo "📍 SIMULAR RENDA:"
echo "POST http://localhost:8080/perfil/simular?receita=5000"
echo "Header: Authorization: Bearer {seu_token}"
echo ""

# ============================================
echo "7️⃣  Acessar o Frontend..."
echo "================================"
echo "Abra no navegador:"
echo "  http://localhost:8000 (ou a porta configurada)"
echo ""
echo "Faça login com email e senha definidos no passo 6"
echo ""

# ============================================
echo "8️⃣  Solução de Problemas..."
echo "================================"
echo ""
echo "❌ ERRO: 'Conexão recusada na porta 5432'"
echo "   → PostgreSQL não está rodando"
echo "   → Inicie o serviço PostgreSQL"
echo ""
echo "❌ ERRO: 'Database financas_pessoais not found'"
echo "   → Banco de dados não foi criado"
echo "   → Execute: psql -U postgres"
echo "              CREATE DATABASE financas_pessoais;"
echo ""
echo "❌ ERRO: 'CORS error' no frontend"
echo "   → CorsConfig.java não foi carregado"
echo "   → Verifique se o arquivo está no caminho correto"
echo "   → Reinicie o servidor Spring Boot"
echo ""
echo "❌ ERRO: 'Token inválido' ou 'Unauthorized'"
echo "   → Token expirou ou está incorreto"
echo "   → Faça login novamente para obter novo token"
echo ""

# ============================================
echo "✨ Tudo pronto! Divirta-se! 🎉"
echo "================================"
echo ""

