spring.application.name=financas-pessoais
server.port=8080
server.servlet.context-path=/api

spring.datasource.url=jdbc:postgresql://localhost:5432/financas_pessoais
spring.datasource.username=postgres
spring.datasource.password=SUA_SENHA_AQUI
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

jwt.secret=SUA_CHAVE_JWT_AQUI_COM_MAIS_DE_32_CARACTERES
jwt.private.key=SUA_CHAVE_JWT_AQUI_COM_MAIS_DE_32_CARACTERES

cors.allowed-origins=http://localhost,http://127.0.0.1

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always
