# Exemplo de configuração do banco
# Copie este arquivo para application.properties e preencha com seus dados locais

spring.datasource.url=jdbc:postgresql://localhost:5432/financas_pessoais_v2
spring.datasource.username=postgres
spring.datasource.password=SUA_SENHA_AQUI

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=10000